apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-poc
  title: Sample Service # optional, human readable component name
  description: My first Backstage catalog item.
  annotations:
    github.com/project-slug: anskrish/backstage-component
spec:
  type: service
  owner: user:anskrish
  lifecycle: experimental
